apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-cm
  namespace: homework
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true 