apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: homework-4
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: install
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, World!" > /init/index.html']
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/sh"]
        args: ["-c", "sed -i 's/80/8000/' /etc/nginx/conf.d/default.conf && ln -sf /homework/* /usr/share/nginx/html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: workdir
          mountPath: /homework
        - name: config-vol
          mountPath: /homework/conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm -f /homework/index.html"]
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        homework: "true"
      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: homework-pvc
      - name: config-vol
        configMap:
          name: homework-cm